buildscript {
    repositories {
        google()
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://jitpack.io' }
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:9.2.1'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
